server:
  port:
    8080
spring:
  redis:
    host: redis-10696.c93.us-east-1-3.ec2.cloud.redislabs.com
    port: 10696
    connect-timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    password: fetoX86nfFlCCpgLilKY0qlocPmjUKIi
